@startuml
hide footbox

title Usuario calcula el puntaje de su jugada ya armada
actor User
participant Mano as ": Mano"
participant Jugada as "jugada: Jugada"
participant Poker as ": Poker"
participant Comodines as ": Comodines"
participant Comodin as ": Comodin"
participant Puntaje as "puntaje: Puntaje"

activate User

User -> Mano: jugar()
activate Mano
Mano --> User: jugada
deactivate Mano

User -> Jugada: modificarPuntaje(puntaje)
activate Jugada

loop todas las cartas involucradas
Jugada -> Poker: modificarPuntaje(puntaje)
activate Poker

Poker -> Puntaje: sumarValorBase(\nvalorBase)
activate Puntaje
deactivate Puntaje
Poker -> Puntaje: multiplicarMultiplicador(\nmultiplicador)
activate Puntaje
deactivate Puntaje

deactivate Poker

end

Jugada -> Puntaje: sumarValorBase(valorBase)
activate Puntaje
deactivate Puntaje
Jugada -> Puntaje: multiplicarMultiplicador(multiplicador)
activate Puntaje
deactivate Puntaje

deactivate Jugada

User -> Comodines: modificarPuntaje(puntaje, jugada, descartes)
activate Comodines

loop todos los comodines

Comodines -> Comodin: modificarPuntaje(\npuntaje, jugada, descates)

note left: El comportamiento de cada comodín puede variar

end

deactivate Comodines

User -> Puntaje: calcularTotal()
activate Puntaje
Puntaje --> User: total
deactivate Puntaje

deactivate User
@enduml